global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'neighborshare-api'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'admin@neighborshare.com'
      password: 'Secret123!'
    static_configs:
      - targets: ['api:8080']